name: rolling-rhino
version: git
summary: Convert Ubuntu into a "rolling release" that tracks the `devel` series
description: |
  Simple shell script to make daily image installs of Ubuntu Desktop,
  and desktop flavours, track the `devel` series.

base: core18
grade: stable
confinement: classic

parts:
  rolling-rhino:
    plugin: dump
    source: .

apps:
  rolling-rhino:
    command: rolling-rhino